// Package phrases provides themed phrases for use in progress indicators.
// It includes a variety of phrase lists inspired by different pop culture themes such as
// Game of Thrones, Star Wars, Harry Potter, Marvel, and Lord of the Rings.

package phrases

var themes = map[string][]string{
	"original":      originalPhrases,
	"gameOfThrones": gameOfThronesPhrases,
	"starWars":      starWarsPhrases,
	"harryPotter":   harryPotterPhrases,
	"marvel":        marvelPhrases,
	"lotr":          lotrPhrases,
}

var originalPhrases = []string{
	"Guess what? You're absolutely amazing!",
	"Fantastic things are headed straight for you!",
	"Hang tight—the best is yet to come!",
	"Spread the joy—flash that dazzling smile!",
	"Unleash your awesomeness—you've got this!",
	"Each second sparkles with new possibilities!",
	"We appreciate your awesomeness—thanks for waiting!",
	"Your radiant vibes light up our world!",
	"Epic awesomeness is brewing—stay tuned!",
	"Glow like the superstar you are!",
	"You're changing the game—way to go!",
	"May your day be filled with magic and wonder!",
	"Brace yourself—awesomeness incoming!",
	"You're among legends—welcome aboard!",
	"You're the reason we're smiling—thanks for joining us!",
	"Hold on to your hat—excitement is brewing!",
	"Your awesomeness knows no bounds!",
	"Ready to rock? Amazing things are happening!",
	"You're a star in our galaxy—shine on!",
	"Magic is in the air, just for you!",
	"High-five! You're fantastic!",
	"Your smile can light up the darkest night!",
	"Get ready to be wowed!",
	"You're a breath of fresh air—thanks for being you!",
	"Great vibes are coming your way!",
	"Prepare for takeoff—good things ahead!",
	"You're unstoppable—keep going!",
	"Your patience is legendary—thanks for waiting!",
	"Adventure awaits—hang in there!",
	"You're the hero of this story!",
	"Big things are coming—stay tuned!",
	"You're an inspiration to us all!",
	"Feeling awesome? You should!",
	"We're brewing something special for you!",
	"Your energy is electric!",
	"You're on fire—in the best way possible!",
	"Get set—awesomeness is about to happen!",
	"The world is brighter with you in it!",
	"You're a trailblazer—keep forging ahead!",
	"Elevating to new heights—thanks to you!",
}

var gameOfThronesPhrases = []string{
	"Winter is coming—great things take time!",
	"Brace yourself—the best is yet to come!",
	"You're the ruler of your own kingdom!",
	"Keep your spirit unburnt—like a true Targaryen!",
	"You know nothing—but amazing things are ahead!",
	"Our appreciation is as endless as the Wall!",
	"Your patience sits upon the Iron Throne!",
	"Adventure awaits beyond the Wall—hang tight!",
	"You’re the hero Westeros needs!",
	"The night is dark, but your smile lights the way!",
	"You're as strong as Valyrian steel!",
	"A Lannister always waits patiently—thank you!",
	"Your awesomeness can't be contained in one realm!",
	"You're a legend in the making—write your story!",
	"Unleash your inner dragon—you've got this!",
	"Magic is in the air—just for you!",
	"Hold fast—your quest is nearly complete!",
	"You're a direwolf among ordinary wolves!",
	"The world is yours to conquer—stay tuned!",
	"Your positivity could defeat any White Walker!",
}

var starWarsPhrases = []string{
	"May the force be with you—great things are coming!",
	"Hang tight—the galaxy awaits you!",
	"You're the droid we've been looking for!",
	"Your patience is stronger than the Force!",
	"Keep shining brighter than a lightsaber!",
	"Adventure is out there—in a galaxy far, far away!",
	"You're a Jedi Master of awesomeness!",
	"The Force is strong with you—stay tuned!",
	"Your positivity can outshine any star!",
	"Ready to jump to lightspeed? Amazing things ahead!",
	"You're the new hope we've been waiting for!",
	"Thank you for waiting—you're our only hope!",
	"The galaxy is brighter with you in it!",
	"Feel the Force—magic is happening!",
	"You're piloting this adventure—full speed ahead!",
	"Your patience brings balance to the Force!",
	"Set phasers to fun—great vibes incoming!",
	"You're as legendary as the Millennium Falcon!",
	"Defying gravity? You must be a Skywalker!",
	"Your journey is epic—keep going!",
}

var harryPotterPhrases = []string{
	"Magic is happening—hang tight!",
	"You're a wizard of awesomeness!",
	"Accio great things! They're coming your way!",
	"Your patience is more powerful than a spell!",
	"Keep shining like the Golden Snitch!",
	"Thank you for waiting—you've got the Marauder's Map!",
	"You're casting spells of positivity!",
	"Your smile could light up Hogwarts!",
	"Adventure awaits on Platform 9¾—stay tuned!",
	"You're as brave as a Gryffindor!",
	"Your journey is magical—keep going!",
	"Expecto patronum—good vibes are coming!",
	"You're brewing something special—just like a potion!",
	"Unlocking chambers of secrets—thanks for waiting!",
	"Your energy is as electric as a lightning bolt scar!",
	"You've got the elder wand of patience!",
	"Flying high on a broomstick of awesomeness!",
	"You're the chosen one—great things ahead!",
	"Thank you for your patience—no invisibility cloak needed!",
	"Your positivity is as contagious as a charm!",
}

var marvelPhrases = []string{
	"You're a superhero of patience—thanks for waiting!",
	"Hang tight—your superpowers are charging!",
	"Ready to assemble? Great things are coming!",
	"You're as mighty as Thor's hammer!",
	"Your awesomeness is incredible—like the Hulk!",
	"Swinging into action—stay tuned!",
	"Your patience is as strong as vibranium!",
	"You're a guardian of greatness!",
	"Your smile can outshine Tony's arc reactor!",
	"You're on a mission—success is near!",
	"Your positivity is more powerful than any Infinity Stone!",
	"Thank you for waiting—you're a real hero!",
	"Your energy is electrifying—like Spider-Man!",
	"Flying high like Iron Man—good things ahead!",
	"You're unstoppable—like Captain Marvel!",
	"Your journey is epic—keep forging ahead!",
	"Magic is in the air—Doctor Strange would be impressed!",
	"You're assembling awesomeness—piece by piece!",
	"Your patience has saved the day!",
	"Get ready—adventure is about to begin!",
}

var lotrPhrases = []string{
	"One does not simply rush greatness—thanks for waiting!",
	"Your journey is epic—like a trek through Middle-earth!",
	"You're a ringbearer of awesomeness!",
	"May your day be filled with hobbit-like joy!",
	"Your patience is as enduring as the elves!",
	"Hang tight—adventure is at your doorstep!",
	"You're the hero of this fellowship!",
	"Your positivity could light up the darkest Mordor!",
	"Keep going—you shall pass!",
	"Thank you for waiting—it's the bravest thing!",
	"Your awesomeness is precious to us!",
	"Mountains may rise and fall, but your patience stands firm!",
	"You're as strong as mithril—keep it up!",
	"Magic is in the air—Gandalf approves!",
	"You're on an unexpected journey—enjoy the ride!",
	"Your spirit is unbreakable—like the One Ring!",
	"The road goes ever on—great things ahead!",
	"Your courage rivals that of Aragorn!",
	"Stay tuned—your quest is nearly complete!",
	"You're the light in dark places—shine on!",
}
